# This is a basic workflow to help you get started with Actions

name: Build Manual (Branches or Tags)

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'The Version (Name) you want to release'
        required: true
      branchOrTag:
        description: 'The Tag or Branch to Build'
        required: true
      repository:
        type: choice
        required: true
        description: The Base Repository for Building
        options:
          - kit-sdq/Artemis
          - ls1intum/Artemis
        
     
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build ${{ github.event.inputs.release-tag }} using ${{ github.event.inputs.branchOrTag }} @ ${{ github.event.inputs.repository }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    env:
      node: 16.x
      java: 17

    steps:
      - uses: actions/checkout@v3.0.2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.branchOrTag }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.node }}'
          cache: 'npm'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ env.java }}'
          cache: 'gradle'
      - name: Production Build
        run: ./gradlew -Pprod -Pwar clean bootWar
        env:
          NODE_OPTIONS: --max_old_space_size=6144

      - name: Copy Dockerfile to Build Directory & Move Artemis.war to Build Directory 
        run: cp src/main/docker/Dockerfile . && mv build/libs/Artemis-*.war ./Artemis.war

      - name: Build Docker Image
        run: docker build --build-arg WAR_PATH=. -t artemis .
  
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        
      - name: Push Image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/artemis:${{ github.event.inputs.release-tag }}
          echo "ImageId will be $IMAGE_ID"
          docker tag artemis $IMAGE_ID
          docker push $IMAGE_ID
          

